# Jekyll configuration for Dotfiles Plus website
title: Dotfiles Plus - AI-Powered Terminal
description: Transform your command line with AI. Natural language commands, intelligent automation, and seamless integration with Claude, ChatGPT, Gemini, and Ollama.
url: https://anivar.github.io
baseurl: /dotfiles-plus
theme: jekyll-theme-cayman

# Theme customization
show_downloads: true
google_analytics: 

# GitHub metadata
github:
  repository_url: https://github.com/anivar/dotfiles-plus
  zip_url: https://github.com/anivar/dotfiles-plus/archive/refs/tags/v2.0.1.zip
  tar_url: https://github.com/anivar/dotfiles-plus/archive/refs/tags/v2.0.1.tar.gz

# SEO
tagline: Transform your terminal with AI - Claude CLI, ChatGPT Terminal, Gemini Command Line & Ollama Integration
keywords: ai terminal, claude cli, chatgpt terminal, gemini command line, ollama shell, bash ai integration, terminal automation, ai powered bash, developer tools, shell enhancement, command line ai, terminal ai assistant

# Navigation
navigation:
  - title: Home
    url: /
  - title: Quick Start
    url: /installation
  - title: Features
    url: /ai-features
  - title: Docs
    url: /docs

# Social links
social:
  github_sponsor: https://github.com/sponsors/anivar
  buymeacoffee: https://buymeacoffee.com/anivar
  
# Social
twitter:
  username: 
  card: summary_large_image